sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - .eslintcache
matrix:
  include:
    - node_js: "8"
      env: LINT=true
    - node_js: "4"
      env: UNIT_TEST=true COVERAGE=false
    - node_js: "6"
      env: UNIT_TEST=true COVERAGE=false
    - node_js: "7"
      env: UNIT_TEST=true COVERAGE=false
    - node_js: "8"
      env: UNIT_TEST=true COVERAGE=true
    - node_js: "8"
      env: INTEGRATION_TEST=storybook-for-react PERCY_PROJECT=percy/storybook-for-react PERCY_TOKEN="$STORYBOOK_FOR_REACT_PERCY_TOKEN"
    - node_js: "8"
      env: INTEGRATION_TEST=storybook-for-vue PERCY_PROJECT=percy/storybook-for-vue PERCY_TOKEN="$STORYBOOK_FOR_VUE_PERCY_TOKEN"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
script:
  - |
      if [ "$LINT" = "true" ]; then
        yarn lint -- --color
      fi
  - |
      if [ "$UNIT_TEST" = "true" ]; then
        yarn test -- --ci --coverage=$COVERAGE --maxWorkers=4 --color
      fi
  - |
      if [ "$INTEGRATION_TEST" != "" ]; then
        yarn test:integration $INTEGRATION_TEST
      fi
