name: Test
on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: master
jobs:
  test:
    name: Test Storybook v8
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b
        id: regex-match
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          text: ${{ inputs.branch }}
          regex: '^[a-zA-Z0-9_/\-]+$'
      - name: Break on invalid branch name
        run: exit 1
        if: ${{ github.event_name == 'workflow_dispatch' && steps.regex-match.outputs && steps.regex-match.outputs.match == '' }}
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: ./prepare-storybook-tests.sh 8
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}/node-${{ matrix.node }}/${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}/node-${{ matrix.node }}/
      - run: yarn
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - run: yarn build
      - name: Debug npm info storybook
        run: |
          echo "Running npx storybook --version..."
          npx storybook --version
      - name: Set up @percy/cli from git
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          cd /tmp
          git clone --branch ${{ inputs.branch }}  --depth 1 https://github.com/percy/cli
          cd cli
          PERCY_PACKAGES=`find packages -type d -mindepth 1 -maxdepth 1 | sed -e 's/packages/@percy/g' | tr '\n' ' '`
          echo "Packages: $PERCY_PACKAGES"
          git log -1
          yarn
          yarn build
          yarn global:link
          cd ${{ github.workspace }} 
          yarn link `echo $PERCY_PACKAGES`
          npx percy --version

      - run: yarn test
